check-coverage: false
exclude:
  - "src/constants.ts"
  - "src/types/**/*.d.ts"
  - "src/types/**/*.ts"
extends: "@istanbuljs/nyc-config-typescript"
include:
  - "src/**/*.ts"
report-dir: "coverage-ts"
reporter:
  - "html"
  - "lcov"
