name: "Deploy: Factory"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn compile"

      - name: "Deploy PRBProxyFactory"
        id: "deploy"
        run: >-
          yarn hardhat --network "${{ github.event.inputs.chain }}"
          deploy:contract:prb-proxy-factory
          --confirmations "${{ github.event.inputs.confirmations }}"
          --set-output true

      - name: "Verify PRBProxyFactory"
        run: >-
          yarn hardhat --network "${{ github.event.inputs.chain }}"
          verify "${{ steps.deploy.outputs.prb-proxy-factory }}"
